services:
  - type: web
    name: matungo-golf
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 --timeout 90 app:app
    autoDeploy: true
    envVars:
      - key: DATA_JSON
        value: inscriptos.json
